server.port=8001

# Use the auth-db service and default DB name authdb
spring.datasource.url=${AUTH_DATABASE_URL:jdbc:postgresql://auth-db:5432/authdb}
spring.datasource.username=${AUTH_POSTGRES_USER:auth_user}
spring.datasource.password=${AUTH_POSTGRES_PASSWORD:auth_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=never

jwt.secret=${AUTH_JWT_SECRET:changeitchangeitchangeitchangeitchangeitchangeitchangeit1234}
jwt.expiration=3600000
