worker_processes 1;

events { worker_connections 1024; }

http {
    log_format microservices_log '{"time":"$time_iso8601","remote_addr":"$remote_addr","request_method":"$request_method","request_uri":"$request_uri","status":$status}';
    access_log /var/log/nginx/access.log microservices_log;

    limit_req_zone $binary_remote_addr zone=perip:10m rate=100r/m;

    upstream auth_service {
        server auth-service:8001;
    }

    upstream resource_service {
        server resource-service:8002;
    }

    upstream notification_service {
        server notification-service:8003;
    }

    server {
        listen 8080;

        error_page 503 @rate_limited;

        location /api/auth/ {
            limit_req zone=perip burst=10 nodelay;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/resources/ {
            limit_req zone=perip burst=10 nodelay;
            proxy_pass http://resource_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/notifications/ {
            limit_req zone=perip burst=10 nodelay;
            proxy_pass http://notification_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location @rate_limited {
            internal;
            add_header Content-Type application/json;
            return 503 '{"status": 503, "message": "Límite de peticiones excedido...", "data": null}';
        }
    }
}
