server.port=8002

# Use the resource-db service and default DB name resourcedb
spring.datasource.url=${RESOURCE_DATABASE_URL:jdbc:postgresql://resource-db:5432/resourcedb}
spring.datasource.username=${RESOURCE_POSTGRES_USER:resource_user}
spring.datasource.password=${RESOURCE_POSTGRES_PASSWORD:resource_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=never

jwt.secret=${AUTH_JWT_SECRET:changeitchangeitchangeitchangeitchangeitchangeitchangeit1234}

# Notification service integration
notification.service.url=${NOTIFICATION_SERVICE_URL:http://notification-service:8003}
